# Pipeline  = Config + Data Processes + Feature Processes + Model
# Use this file to store common pipelines which can be used for various tasks

- tabular_classification:
    _id: null
    model_universe
    process:
    - data_cleaning
    - feature_creation
    - feature_selection
    - model_selection
